### PR TITLE
Removing the dependency on k

### PR DESCRIPTION
**Pull request by RohinMohanadas**
The paper doesnt have a dependency on cluster centers and the latent dimensionality.

### CODE REVIEW

**Comment by kborer** [comment]
thanks @RohinMohanadas

**Comment by nickmarton** [comment]
Great catch, I imposed this constraint for convenience and forgot to switch it back. @RohinMohanadas can you squash into a single commit?

**Comment by RohinMohanadas** [comment]
I don't know if I can do that with the existing pull request, should I raise a new one ?

**Comment by penguinland** [comment]
For future reference, @nickmarton, I think you can squash it yourself when you merge a PR.

**Pull request closed without merging**
